/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
    DB: D1Database;
    ENVIRONMENT?: string;
    BUBBLEWASH_DATABASE_DRIVER?: string;
    BUBBLEWASH_PUBLIC_URL?: string;
    BUBBLEWASH_DISABLE_DEMO_LOGIN?: string;
    BUBBLEWASH_TRUST_EDGE_HEADERS?: string;
    BUBBLEWASH_MIGRATION_ENABLED?: string;
    BUBBLEWASH_RELEASE_SHA?: string;
    BUBBLEWASH_DEPLOYMENT_PHASE?: string;
    BUBBLEWASH_SESSION_SECRET: string;
    BUBBLEWASH_MAINTENANCE_TOKEN: string;
    BUBBLEWASH_HOUSEHOLD_LAUNCH_DATE?: string;
    BUBBLEWASH_LEGAL_ENTITY_NAME?: string;
    BUBBLEWASH_DPC_REGISTRATION_NUMBER?: string;
    NEXT_PUBLIC_BUBBLEWASH_ONLINE_PAYMENTS_ENABLED?: string;
    NEXT_PUBLIC_BUBBLEWASH_AUTOMATED_UPDATES_ENABLED?: string;
    PAYSTACK_SECRET_KEY?: string;
    RESEND_API_KEY?: string;
    BUBBLEWASH_EMAIL_FROM?: string;
    BUBBLEWASH_OPERATIONS_EMAIL?: string;
    WHATSAPP_API_VERSION?: string;
    WHATSAPP_ACCESS_TOKEN?: string;
    WHATSAPP_PHONE_NUMBER_ID?: string;
    WHATSAPP_EARLY_ACCESS_TEMPLATE?: string;
    WHATSAPP_PRIVACY_TEMPLATE?: string;
    WHATSAPP_BOOKING_TEMPLATE?: string;
    WHATSAPP_OPERATIONS_TEMPLATE?: string;
    BUBBLEWASH_OPERATIONS_WHATSAPP?: string;
    LOGIN_RATE_LIMITER: RateLimit;
    PUBLIC_WRITE_RATE_LIMITER: RateLimit;
    PAYMENT_RATE_LIMITER: RateLimit;
    PUBLIC_READ_RATE_LIMITER: RateLimit;
    DISPATCH_RATE_LIMITER: RateLimit;
  }
}
