"use client";
import { FormEvent, useEffect, useState } from "react";
import { postJSON, formatMoney } from "@/lib/public-ui";
type Account = { email: string; name: string; role: string; entityId: string; status: string };
export function StaffAccountPanel() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [status, setStatus] = useState("");
  const [link, setLink] = useState("");
  const [pending, setPending] = useState(false);
  async function load() { const response = await fetch("/api/staff/accounts"); if (!response.ok) throw new Error("Unable to load staff access."); setAccounts((await response.json()).accounts); }
  useEffect(() => { let active = true; fetch("/api/staff/accounts").then(async (response) => { if (!response.ok) throw new Error("Unable to load staff access."); const data = await response.json(); if (active) setAccounts(data.accounts); }).catch((e) => { if (active) setStatus(e.message); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setLink("");
    try { const data = await postJSON<{ activationPath: string; message: string }>("/api/staff/accounts", Object.fromEntries(new FormData(event.currentTarget))); setLink(`${window.location.origin}${data.activationPath}`); setStatus(data.message); await load(); }
    catch (e) { setStatus(e instanceof Error ? e.message : "Unable to save access."); } finally { setPending(false); }
  }
  async function suspend(email: string) { setPending(true); try { await postJSON("/api/staff/accounts", { action: "suspend", email }); await load(); setStatus("Account suspended. Existing sessions have been revoked."); } catch (e) { setStatus(e instanceof Error ? e.message : "Unable to suspend access."); } finally { setPending(false); } }
  return <section className="staffAccountPanel"><h2>Individual staff access</h2><p>Roster records describe people and capacity. These accounts control sign-in. Each vendor or rider must use their own account bound to an approved roster ID.</p><div className="staffCaseList">{accounts.map((account) => <div key={account.email} className="staffCaseRow"><strong>{account.name}</strong><span>{account.email} · {account.role}</span><span>{account.status}</span><button className="button secondary" disabled={pending || account.status === "suspended"} onClick={() => suspend(account.email)}>Suspend</button></div>)}</div><details><summary>Create or reset individual access</summary><form onSubmit={submit}><div className="formGrid two"><label>Name<input name="name" required maxLength={100} /></label><label>Work email<input name="email" type="email" required /></label><label>Role<select name="role"><option value="support">Support</option><option value="vendor">Vendor</option><option value="driver">Driver</option></select></label><label>Roster entity ID<input name="entityId" placeholder="Required for vendors and riders" /></label></div><p>To reset an existing account, enter its current role and roster binding. A reset immediately revokes its sessions.</p><button className="button primary" disabled={pending}>{pending ? "Saving…" : "Create activation link"}</button></form></details>{link ? <p><code>{link}</code></p> : null}<p role="status">{status}</p></section>;
}
type Invoice = { invoiceId: string; totalMinor: number; balanceMinor: number; status: string; lines: { label: string; amountMinor: number }[]; entries: { id: string; kind: string; reference: string; amountMinor: number }[] };
export function StaffInvoicePanel({ orderId, admin }: { orderId: string; admin: boolean }) {
  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [status, setStatus] = useState("Loading invoice…"); const [pending, setPending] = useState(false);
  useEffect(() => { let active = true; fetch(`/api/orders/invoice?orderId=${encodeURIComponent(orderId)}`, { cache: "no-store" }).then(async (r) => { if (!r.ok) throw new Error("Unable to load invoice."); const data = await r.json(); if (active) { setInvoice(data.invoice); setStatus(data.invoice ? "" : "An invoice is issued when verified intake weight is recorded."); } }).catch((e) => { if (active) setStatus(e.message); }); return () => { active = false; }; }, [orderId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setPending(true); try { const data = await postJSON<{ invoice: Invoice }>("/api/orders/invoice", { ...Object.fromEntries(new FormData(form)), orderId }); setInvoice(data.invoice); setStatus("Ledger entry recorded."); form.reset(); } catch (e) { setStatus(e instanceof Error ? e.message : "Unable to record entry."); } finally { setPending(false); } }
  return <section className="invoicePanel"><h3>{invoice?.invoiceId || "Itemized invoice"}</h3>{invoice ? <><dl className="recordList">{invoice.lines.map((line, index) => <div key={index}><dt>{line.label}</dt><dd>{formatMoney(line.amountMinor / 100)}</dd></div>)}<div><dt>Total</dt><dd>{formatMoney(invoice.totalMinor / 100)}</dd></div><div><dt>Balance · {invoice.status}</dt><dd>{formatMoney(invoice.balanceMinor / 100)}</dd></div></dl>{invoice.entries.map((entry) => <p key={entry.id}>{entry.kind} · {formatMoney(entry.amountMinor / 100)} · {entry.reference}</p>)}{admin ? <details><summary>Reconcile payment, credit or refund</summary><form onSubmit={submit}><label>Entry<select name="kind"><option value="payment">Payment received</option><option value="credit">Approved credit</option><option value="refund">Refund completed</option></select></label><label>Amount (GHS)<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Unique bank/provider reference<input name="reference" minLength={3} maxLength={120} required /></label><label>Reconciliation note<textarea name="note" maxLength={600} required /></label><p>Record a refund only after it has been completed through the bank or payment provider.</p><button className="button primary" disabled={pending}>Record entry</button></form></details> : null}</> : admin ? <form onSubmit={submit}><input type="hidden" name="kind" value="issue" /><label>Verified intake weight (kg)<input name="weight" type="number" min="0.01" max="10000" step="0.01" required /></label><label>Agreed custom route fee (GHS)<input name="routeFee" type="number" min="0" step="0.01" placeholder="Only required for custom routes" /></label><label>Evidence and approval note<textarea name="note" minLength={10} maxLength={600} required /></label><button className="button primary" disabled={pending}>Issue verified invoice</button></form> : null}<p role="status">{status}</p></section>;
}
export function CustomerDecisionPanel({ ticketId, action, onSaved }: { ticketId: string; action: string; onSaved: () => void }) {
  const [status, setStatus] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); try { const result = await postJSON<{ message: string }>("/api/customer/decision", { ...Object.fromEntries(new FormData(event.currentTarget)), ticketId }); setStatus(result.message); onSaved(); } catch (e) { setStatus(e instanceof Error ? e.message : "Unable to apply decision."); } finally { setPending(false); } }
  return <section className="invoicePanel"><h3>Decide customer {action} request</h3><form onSubmit={submit}><label>Decision<select name="decision"><option value="approve">Approve and apply</option><option value="decline">Decline with explanation</option></select></label><label>Decision note<textarea name="note" maxLength={600} required /></label><button className="button primary" disabled={pending}>Apply decision</button><p role="status">{status}</p></form></section>;
}
